default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  database: <%= Rails.application.secrets[:db_name] %>
  username: <%= Rails.application.secrets[:db_username] %>
  password: <%= Rails.application.secrets[:db_password] %>
development:
  <<: *default
production:
  <<: *default
test:
  <<: *default
  database: store_test
