shared:
  email_from: 'admin@example.com'
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_username: <%= ENV["DB_USERNAME"] %>
  db_password: <%= ENV["DB_PASSWORD"] %>
  db_name: <%= ENV["DB_NAME"] %>

development:
test:
production:
